services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db

  tests:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    command: python -m unittest discover tests -v

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=products
      - POSTGRES_USER=admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5433

volumes:
  postgres_data: